application: fswd-p2-multiuser-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: writehere.app

libraries:
- name: jinja2
  version: latest

- name: markupsafe
  version: latest
