import webapp2

import handlers

app = webapp2.WSGIApplication([('/', handlers.MainPage),
                               (handlers.blogurl + '/?', handlers.BlogFront),
                               (handlers.blogurl + '/post/([0-9]+)',
                                handlers.PostPage),
                               (handlers.blogurl + '/post/([0-9]+)/delete',
                                handlers.DeletePostPage),
                               (handlers.blogurl + '/post/([0-9]+)/edit',
                                handlers.EditPostPage),
                               (handlers.blogurl + '/post/([0-9]+)/like',
                                handlers.LikePostPage),
                               (handlers.blogurl + '/post/([0-9]+)/dislike',
                                handlers.DislikePostPage),
                               (handlers.blogurl + '/post/([0-9]+)/comment',
                                handlers.CommentPostPage),
                               (handlers.blogurl + '/comment/([0-9]+)/delete',
                                handlers.DeleteCommentPage),
                               (handlers.blogurl + '/comment/([0-9]+)/edit',
                                handlers.EditCommentPage),
                               (handlers.blogurl + '/newpost',
                                handlers.NewPost),
                               (handlers.blogurl + '/user/(.*)',
                                handlers.UserPage),
                               ('/signup', handlers.Register),
                               ('/login', handlers.Login),
                               ('/logout', handlers.Logout),
                               ],
                              debug=True)
